spring:
  #应用名称，集群名称需要一致
  application.name: eureka-consumer
  
server:
  port: 8021

eureka:
  instance:
    #可以用hostname注册
    #hostname: localhost
    #可以用ip注册
    perferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  #向该地址注册服务
  client.serviceUrl.defaultZone: http://localhost:8010/eureka/