spring:
  application.name: eureka-server
  
server:
  port: 8010

eureka:
  instance.hostname: localhost
  client:
    serviceUrl.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #Standalone Mode
    register-with-eureka: false 
    fetch-registry: false
  #server:
    #enable-self-preservation: false
