spring:
  application.name: eureka-server
  
server:
  port: 8010

eureka:
  instance.hostname: localhost
  client:
    serviceUrl.defaultZone: http://localhost:8010/eureka/
    register-with-eureka: false 
    fetch-registry: false
  #server:
    #enable-self-preservation: false
