spring:
  application.name: config-server
  #profiles.active: native
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/321118/my-spring-cloud-sample
          search-paths: sample3/config-repo/repo # git仓库地址下的相对地址，可以配置多个，用,分割。
          #username: 
          #password: 

server:
  port: 8030
  
management.security.enabled: false #忽略权限拦截看/env
